# Generated by Django 2.0.3 on 2018-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180326_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='source',
            field=models.CharField(default='', max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='blog_posts', to='files.Tag'),
        ),
    ]
